#!/bin/bash

if [ -e "${1}/extensions/bun/main.js" ]; then
    export BUN_INSTALL="${1}/extensions/bun/_runtime"
    $BUN_INSTALL/bin/bun run --inspect "${1}/extensions/bun/main.js"
else
    "${1}/extensions/bun/main-app" $2 $3 $4
fi
