#!/usr/bin/env bash
# Based on code by https://github.com/malipetek - hey you did a brilliant job!
MACOS="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CONTENTS="$(dirname "$MACOS")"
exec "${MACOS}/main" --path="${CONTENTS}/Resources" --enable-extensions=true
